### ISSUE TITLE
CLI Image Export Fails

### ISSUE THREAD

**Issue by nathan-vu** [oracle/bmcs-cli#4]
### Issue
The `bmcs compute image export` takes in a `--destination-type` switch which says where to place the exported image; the value passed in as a parameter is a JSON string and can identify either an Object Storage URI or a Object Storage tuple of (namespace, bucket name, object name)

Currently this CLI command fails to export an image using either the URI or tuple, even though the JSON string is formatted properly as per the CLI help documentation, and an `Invalid Parameter` error is passed back.

### Repro Steps
Example command (with dummy Image ID and Destination URI):

```
bmcs compute image export --image-id "ocid1.image.oc1.phx....." \
--destination-type ' { "destinationUri": "https://objectstorage.us-phoenix-1.oraclecloud.com/....", "destinationType": "objectStorageUri" }'
```

**Comment by jodoglevy** [comment]
Fixed in v2.4.6
