### ISSUE TITLE
Package fails to install on Fedora 26

### ISSUE THREAD

**Issue by bgilbert** [oracle/bmcs-cli#5]
On Fedora 26, running `pip install oraclebmc-cli` in a fresh virtualenv produces a [build failure](https://github.com/oracle/bmcs-cli/files/1206631/log.txt) in the `cryptography` package.  `bmcs-cli`'s `setup.py` depends on `cryptography==1.8.1`, but `cryptography` < 1.8.2 will not build with OpenSSL &ge; 1.1.0f (https://github.com/pyca/cryptography/pull/3603).  If I install `oraclebmc-cli` from a Git checkout that has the version pins removed from `setup.py`, the package installs and works properly.

Please consider dropping the version pins from `setup.py`, and instead specifying only the minimum required versions of dependencies.  Pinning is [not considered best practice](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires) and tends to produce problems like this one.

**Comment by mross22** [comment]
Thanks for reporting this.  I will make the change to upgrade to cryptography 1.8.2 (assuming there are no regressions in our tests) which should fix your immediate install issue.

As for pinning, I understand the point being made in the linked doc about 'users not gaining the benefit of dependency upgrades' but we are making that trade off in favor of greater stability by guaranteeing that our users have the exact dependency versions that we have tested against.  It may be something we are willing to reconsider in the future if we see the burden of issues like this outweighing the concern that varying dependencies may cause instability in our own package.

**Comment by brunoborges** [comment]
@mross22 please check your email :-)

**Comment by jodoglevy** [comment]
Fixed in v2.4.6
