### ISSUE TITLE
pip install oraclebmc-cli  fails on clean install

### ISSUE THREAD

**Issue by IoTMike** [oracle/bmcs-cli#9]
Summary:  upon executing `pip install oracle-bmcs-cli/oraclebmc_cli-2.4.5-py2.py3-none-any.whl` or  `pip install oraclebmc-cli` (with or without sudo), error returned:

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-iBfi6V/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-LBnltB-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-iBfi6V/cryptography/

Environment:  Oracle BMCS: BM.Standard1.36
Image:  Oracle-Linux-7.3-2017.07.17-0
Docs used:  https://docs.us-phoenix-1.oraclecloud.com/Content/API/SDKDocs/cli.htm

Session dialog:
-------
[opc@ml1 ~]$ uname -a
Linux ml1 4.1.12-94.3.8.el7uek.x86_64 #2 SMP Fri Jun 30 10:40:13 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux

[opc@ml1 ~]$ sudo yum install libffi-devel python-devel openssl-devel
Loaded plugins: langpacks, ulninfo
Package libffi-devel-3.0.13-18.el7.x86_64 already installed and latest version
Package python-devel-2.7.5-58.0.1.el7.x86_64 already installed and latest version
Package 1:openssl-devel-1.0.2k-8.0.1.el7.x86_64 already installed and latest version
Nothing to do

[opc@ml1 ~]$ sudo easy_install pip
Searching for pip
Best match: pip 9.0.1
Processing pip-9.0.1-py2.7.egg
pip 9.0.1 is already the active version in easy-install.pth
Installing pip script to /usr/bin
Installing pip2.7 script to /usr/bin
Installing pip2 script to /usr/bin
Using /usr/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip

[opc@ml1 ~]$ pip install virtualenv
Requirement already satisfied: virtualenv in /usr/lib/python2.7/site-packages

[opc@ml1 ~]$ sudo pip install oracle-bmcs-cli/oraclebmc_cli-2.4.5-py2.py3-none-any.whl
Processing ./oracle-bmcs-cli/oraclebmc_cli-2.4.5-py2.py3-none-any.whl
Requirement already satisfied: pytz==2016.7 in /usr/lib/python2.7/site-packages (from oraclebmc-cli==2.4.5)
Collecting oraclebmc==1.3.5 (from oraclebmc-cli==2.4.5)
  Downloading oraclebmc-1.3.5-py2.py3-none-any.whl (287kB)
    100% |████████████████████████████████| 296kB 3.8MB/s
Collecting click==6.7 (from oraclebmc-cli==2.4.5)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting certifi (from oraclebmc-cli==2.4.5)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Requirement already satisfied: six==1.10.0 in /usr/lib/python2.7/site-packages (from oraclebmc-cli==2.4.5)
Collecting cryptography==1.8.1 (from oraclebmc-cli==2.4.5)
  Downloading cryptography-1.8.1.tar.gz (423kB)
    100% |████████████████████████████████| 430kB 2.7MB/s
Collecting terminaltables==3.1.0 (from oraclebmc-cli==2.4.5)
  Using cached terminaltables-3.1.0.tar.gz
Collecting python-dateutil==2.5.3 (from oraclebmc-cli==2.4.5)
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting httpsig-cffi==15.0.0 (from oraclebmc-cli==2.4.5)
  Using cached httpsig_cffi-15.0.0-py2.py3-none-any.whl
Collecting requests[security]==2.11.1 (from oraclebmc-cli==2.4.5)
  Using cached requests-2.11.1-py2.py3-none-any.whl
Collecting configparser==3.5.0 (from oraclebmc-cli==2.4.5)
  Using cached configparser-3.5.0.tar.gz
Requirement already satisfied: idna>=2.1 in /usr/lib/python2.7/site-packages (from cryptography==1.8.1->oraclebmc-cli==2.4.5)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography==1.8.1->oraclebmc-cli==2.4.5)
Requirement already satisfied: packaging in /usr/lib/python2.7/site-packages (from cryptography==1.8.1->oraclebmc-cli==2.4.5)
Requirement already satisfied: setuptools>=11.3 in /usr/lib/python2.7/site-packages (from cryptography==1.8.1->oraclebmc-cli==2.4.5)
Requirement already satisfied: enum34 in /usr/lib/python2.7/site-packages (from cryptography==1.8.1->oraclebmc-cli==2.4.5)
Requirement already satisfied: ipaddress in /usr/lib/python2.7/site-packages (from cryptography==1.8.1->oraclebmc-cli==2.4.5)
Requirement already satisfied: cffi>=1.4.1 in /usr/lib64/python2.7/site-packages (from cryptography==1.8.1->oraclebmc-cli==2.4.5)
Requirement already satisfied: pyOpenSSL>=0.13; extra == "security" in /usr/lib64/python2.7/site-packages (from requests[security]==2.11.1->oraclebmc-cli==2.4.5)
Collecting ndg-httpsclient; extra == "security" (from requests[security]==2.11.1->oraclebmc-cli==2.4.5)
  Using cached ndg_httpsclient-0.4.2.tar.gz
Collecting pyasn1; extra == "security" (from requests[security]==2.11.1->oraclebmc-cli==2.4.5)
  Using cached pyasn1-0.3.2-py2.py3-none-any.whl
Requirement already satisfied: pyparsing in /usr/lib/python2.7/site-packages (from packaging->cryptography==1.8.1->oraclebmc-cli==2.4.5)
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography==1.8.1->oraclebmc-cli==2.4.5)
Installing collected packages: certifi, ndg-httpsclient, pyasn1, requests, cryptography, python-dateutil, httpsig-cffi, configparser, oraclebmc, click, terminaltables, oraclebmc-cli
  Running setup.py install for ndg-httpsclient ... done
  Found existing installation: requests 2.6.0
    DEPRECATION: Uninstalling a distutils installed project (requests) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling requests-2.6.0:
      Successfully uninstalled requests-2.6.0
  Running setup.py install for cryptography ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-iBfi6V/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-LBnltB-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/__about__.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/__init__.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/exceptions.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/fernet.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/utils.py -> build/lib.linux-x86_64-2.7/cryptography
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat
    copying src/cryptography/hazmat/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat
    creating build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/base.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/extensions.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/general_name.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/name.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/oid.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/multibackend.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings
    copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/serialization.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/backend.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/ciphers.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/commoncrypto
    copying src/cryptography/hazmat/bindings/commoncrypto/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/commoncrypto
    copying src/cryptography/hazmat/bindings/commoncrypto/binding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/commoncrypto
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/interfaces
    copying src/cryptography/hazmat/primitives/interfaces/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/interfaces
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    running egg_info
    writing requirements to src/cryptography.egg-info/requires.txt
    writing src/cryptography.egg-info/PKG-INFO
    writing top-level names to src/cryptography.egg-info/top_level.txt
    writing dependency_links to src/cryptography.egg-info/dependency_links.txt
    writing entry points to src/cryptography.egg-info/entry_points.txt
    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
    creating build/temp.linux-x86_64-2.7
    generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
    generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    unable to execute gcc: No such file or directory
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-iBfi6V/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-LBnltB-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-iBfi6V/cryptography/
-------

Notes:
1) Docs do not state to use sudo, get many permission violations without.
2) Same result when using `pip install oraclebmc-cli` instead of github zip download.
3) Tried with and without performing `sudo yum update` with no change, although running the yum update breaks connecting via iscsi to block devices.

**Comment by mross22** [comment]
The documentation is out of date in this case and we have a ticket to update it internally, sorry for the inconvenience.

You will need to add 'gcc' to your 'yum install' command like so:
sudo yum install libffi-devel python-devel openssl-devel **gcc**

As for needing sudo to execute pip install oraclebmc_cli, that will not be the case if you are installing into a virtualenv that resides in a folder that you have permissions to access.  Based on the commands pasted above it looks like you are installing virtualenv (pip install virtualenv) but not creating a new virtualenv and installing 'oraclebmc_cli' in it.  Thus you are getting permissions errors when trying to update packages in your system python installation (/usr/lib/python2.7/site-packages).

The Oracle Linux 6 docs are explicit about setting up a virtualenv but it looks like the Oracle Linux 7 instructions should be improved to make this clearer.  To install oraclebmc_cli in a virtualenv you can execute the following commands (note this is basically the last few lines of the OEL 6 instructions):

`sudo pip install virtualenv`
`# note you do not need the -p option below like you do for OEL 6`
`# because you can just use the default system python executable to create your virtualenv`
`virtualenv cli_env`
`cli_env/bin/activate`
`pip install oraclebmc-cli`

**Comment by IoTMike** [comment]
Thanks Mike.  Duh...should have figured gcc out.

Also in the docs:

3. (Optional) Create a directory for storing your virtual environments.
`/mkdir/myvirtualspaces/virtualenvs`

At least that one's pretty self evident.
Cheers.

**Comment by ghoddg** [comment]
Hi,
I am trying to install oci-cli but getting below error, Please help.

sudo pip install oci_cli-2.7.0-py2.py3-none-any.whl
Processing ./oci_cli-2.7.0-py2.py3-none-any.whl
Collecting oci==2.8.0 (from oci-cli==2.7.0)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff647143bd0>: Failed to establish a new connection: [Errno 113] No route to host',)': /simple/oci/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff647143d50>: Failed to establish a new connection: [Errno 113] No route to host',)': /simple/oci/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff647143910>: Failed to establish a new connection: [Errno 113] No route to host',)': /simple/oci/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff647143710>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/oci/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff647138190>: Failed to establish a new connection: [Errno 113] No route to host',)': /simple/oci/
  Could not find a version that satisfies the requirement oci==2.8.0 (from oci-cli==2.7.0) (from versions: )
No matching distribution found for oci==2.8.0 (from oci-cli==2.7.0)
